64 testing character service test briiite
FullSol/amplifier pull request #101
Opened 2022-05-25 19:12 UTC by briiitelord

Character service test with CRUD operations

also added (done for testing):

- repository layer (no implementations)
- service layer (no implementations)
- model

2022-05-25 22:27 UTC, pyaeger requested changes
Please keep pull requests focused on one issue as per sprint meeting discussions. Thanks!

2022-05-25 22:27 UTC, pyaeger commented on src/main/java/com/amplifier/repositories/CharacterRepositoryImpl.java
> +}
FYI: Repository implementations are not required due to Spring framework. Please delete.

2022-05-26 02:11 UTC, FullSol requested changes
Please see the response from @pyaeger

2022-05-26 13:34 UTC, FullSol approved these changes

2022-05-26 20:59 UTC, merged