Create test for character controller
FullSol/amplifier pull request #56
Opened 2022-05-22 22:44 UTC by jularmerme

Create unit tests for Character Controller

2022-05-22 23:31 UTC, pyaeger commented on src/main/java/com/amplifier/models/Character.java
> +@ApiModel(value = "User", description = "This model serves as the basic model for all user characters entity API operations.")
On line 16, shouldn't 
`value = "User" `
be
`value = "Character"`
???

2022-05-23 03:21 UTC, FullSol requested changes

2022-05-23 03:21 UTC, FullSol commented on src/test/java/com/amplifier/controllers/CharacterControllerTest.java
> +    return true;
This should actually be testing the response from the controller. Write as if there is code in the controller (even though there is not). The test will fail, but when the next person comes and does the user controller the test should pass without any changes to the test.

2022-05-25 14:59 UTC, pyaeger approved these changes
Thanks for the work!

2022-05-25 15:07 UTC, FullSol commented
Please explain what happened here.
There are 39 files that will overwrite whatever is in the dev branch if this is merged in.

I see: [Fix Merge branch conflicts](https://github.com/FullSol/amplifier/pull/56/commits/b29fd61f589eea5b9441ade8ee72853cd43e4a85)

But that would not show the changes like this if it was done with the commands:

```
git switch dev 
git pull 
git switch (your working branch)
git merge dev
```
that would only show the changes you made (not all changes).

I am considering this unsafe to merge until we know how this will affect the dev branch.

2022-05-25 15:18 UTC, FullSol commented
Okay, so looking at the commit history you went through and resolved the merge conflict AFTER you did the pull request. That is the job of Patrick and I as a part of the code review. I am reverting the merge and I will review the merge e conflicts.

2022-05-25 15:30 UTC, pyaeger commented
Sorry guys. I just don't understand enough to be an effective Gitflow Master.

2022-05-25 15:37 UTC, FullSol commented
I looked at the code you wrote Julian and it only needed some minor edits - I've made those. However, GitHub is not giving me the option to review the code before merging it in the way I need to in order to make sure we are not overwriting code everyone else wrote.

You probably did the merge correctly when you reviewed it, but it would be irresponsible for me to merge in the code if I wasn't sure about it.

So, what I am going to do it remove this branch and create a new one. I have your code and I am going to have to complete another pull request. You will have errors, ignore them.

Go ahead and go to dev on your machine and run the `git pull` command. I'll get everything else setup.

@jularmerme

2022-05-25 15:38 UTC, closed without merging

2022-05-25 15:38 UTC, FullSol reviewed
see previous comment on PR