44 testing userrole controller test
FullSol/amplifier pull request #75
Opened 2022-05-24 12:57 UTC by L3viathon

Started user role controller integration test.

(I also linked the wrong issue and branch with this... my mistake, and will fix).

2022-05-24 13:00 UTC, pyaeger approved these changes
Thank you.

2022-05-24 16:10 UTC, FullSol commented
Did you want this reviewed now? @L3viathon

2022-05-24 17:08 UTC, FullSol requested changes
Looks good so far. Just need to finish it up for approval.

2022-05-25 23:15 UTC, FullSol approved these changes

2022-05-25 23:16 UTC, merged