Starting integration testing comment controller layer.
FullSol/amplifier pull request #76
Opened 2022-05-24 13:22 UTC by L3viathon

2022-05-24 14:55 UTC, pyaeger approved these changes
Thank you.

2022-05-24 16:48 UTC, FullSol requested changes

2022-05-24 16:48 UTC, FullSol commented on src/test/java/com/amplifier/controllers/CommentControllerIntTest.java
> +
Good so far.

2022-05-24 16:48 UTC, FullSol commented on src/test/java/com/amplifier/controllers/CommentControllerIntTest.java
> +
Pending completion.

2022-05-26 12:05 UTC, L3viathon commented
More tests needed to be added with Julian's additional methods.

2022-05-26 12:08 UTC, FullSol approved these changes

2022-05-26 12:08 UTC, FullSol commented on src/test/java/com/amplifier/controllers/CommentControllerIntTest.java
> +                            .put("/api/v1/comment?id=3")
Is patch available here?

2022-05-26 12:08 UTC, FullSol commented on src/test/java/com/amplifier/controllers/CommentControllerIntTest.java
> +                            .put("/api/v1/comment?id=3")
Same here

2022-05-26 12:08 UTC, FullSol commented
@L3viathon i left a comment, but approving

2022-05-26 12:08 UTC, merged