work on ImgPostControllerIntTest
FullSol/amplifier pull request #78
Opened 2022-05-24 14:49 UTC by pyaeger

Five tests failed accordingly. Need more time to implement creation and modification tests.

I had mistakenly worked on the ImgPost model. Submitting that in case that's helpful as a starting point for whoever is assigned.

2022-05-24 14:52 UTC, pyaeger commented
I don't know why there were changes in the .classpath file.

2022-05-24 16:44 UTC, FullSol submitted a review, later dismissed
Looks good. And looks like you wrote out all of the code for the model. Easy mode for whoever gets assigned to that! I think I did like two of them now...

2022-05-24 18:53 UTC, FullSol commented
What happened here? Looks like User model was pasted on top of the ImgPost model?

2022-05-24 18:57 UTC, pyaeger commented
GitHub showed there was a conflict (overlapping redundant sectiosn) between my to-be-merged branch ImgPost model and dev ImgPost model. I went in through the web editor here in GitHub as suggested by GitHub and resolved the conflict by removing my sections.

2022-05-24 18:58 UTC, FullSol commented
> 

Is there an undo function? Whatever was there before I approved.

2022-05-24 19:00 UTC, pyaeger commented
When I worked on the ImgPost model it was empty. Looks like GitHub now sees the model now in dev and saw that the ImgPost model I submitted in my pull request was overlapping/conflicting with the dev ImgPost. It asked that I resolve the conflict in order for the pull request to proceed.

2022-05-24 19:11 UTC, FullSol commented
> When I worked on the ImgPost model it was empty. Looks like GitHub now sees the model now in dev and saw that the ImgPost model I submitted in my pull request was overlapping/conflicting with the dev ImgPost. It asked that I resolve the conflict in order for the pull request to proceed.

I see what is happening. I thought you made the changes to Impost, but that was me last night... But when there are merging differences the code needs to be reviewed and the more accurate code needs to be accepted.

But this is why we have reviews, so not a big deal

Just an FYI the ImgPost model would be obliterated when this branch was merged. I'm not sure how to undo the merge you just made, but I'm sure we can figure it out.

2022-05-24 19:14 UTC, FullSol commented
I will say though, in the future, let's not edit code once an approval has been made unless changes are requested. Doing so invalidates the approver's review and if it is not seen fast enough we may run into an issue.

2022-05-24 19:18 UTC, pyaeger commented
Okay sounds good. Will do going forward. 

(I don't think the merge will obliterate your ImgPost model in dev but rather **_merge_** the few sections that remain in my proposed pull request ImgPost model into yours now that there are no conflicts/duplicate lines.)

2022-05-24 19:26 UTC, FullSol commented
> (I don't think the merge will obliterate your ImgPost model in dev but rather **_merge_** the few sections that remain in my proposed pull request ImgPost model into yours now that there are no conflicts/duplicate lines.)

No, that is not correct in this case. If you merge a pull request with  newer information and the old code is not present it will overwrite the branch you are merging into. That error you were getting from GitHub was the chance to do what you are talking about and choosing what code to keep and what code to remove.

I've reverted that change and fixed any errors so the code should be fine to merge not, If not it's my fault and I'll make a ticket to fix it later.

2022-05-24 19:28 UTC, pyaeger commented
Okay, sorry for problem there. Ugh.

2022-05-24 19:29 UTC, FullSol commented
Not a problem at all. Learning experience! Sort of the point of all of this.

2022-05-24 19:35 UTC, FullSol approved these changes

2022-05-24 19:35 UTC, FullSol commented on .classpath
> -	<classpathentry kind="src" path="target\generated-sources\annotations">
Was this removed? I thought I approved the changes that were here before?

2022-05-25 04:36 UTC, pyaeger commented
Is this still in the queue for merging pending the final review? Thanks for the clarification. :)

2022-05-25 05:05 UTC, L3viathon requested changes

2022-05-25 05:05 UTC, L3viathon commented on src/test/java/com/amplifier/controllers/ImgPostControllerIntTest.java
> +		mockImgPost1 = new ImgPost(1, "ImageTest");
For "`mockImgPost1 = new Impost(1, "ImageTest");`"?, "`imageTest`" needs to be a mockUser (aka author). You will have to create a mock object of user to add when initializing `mockImgPost1`. I've added the ImgPost constructor for your reference below. 

```
 public ImgPost(String imgLocation, User author) {
        this.imgLocation = imgLocation;
        this.author = author;
    }
```

2022-05-25 05:05 UTC, L3viathon commented on src/test/java/com/amplifier/controllers/ImgPostControllerIntTest.java
> +                            .get("/api/imgpost?id=xxxxxxxxxxxxxxxxxxxxxxx");
"`id=xxxxxxxxxxxxxxxxxxxx`" should be 1 (for ex). This id is referring to imgPost id.

2022-05-25 05:05 UTC, L3viathon commented on src/test/java/com/amplifier/controllers/ImgPostControllerIntTest.java
> +                            .delete("/api/v1/imgpost?id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
"`id=xxxxxxxxxxxxxxxxxxxx`" should be 1 (for ex). This id is referring to imgPost id.

2022-05-25 05:05 UTC, L3viathon commented on src/test/java/com/amplifier/controllers/ImgPostControllerIntTest.java
> +                            .delete("/api/v1/imgpost?id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
"`id=xxxxxxxxxxxxxxxxxxxx`" should be 1 (for ex). This id is referring to imgPost id.

2022-05-25 12:45 UTC, pyaeger commented on src/test/java/com/amplifier/controllers/ImgPostControllerIntTest.java
> +		mockImgPost1 = new ImgPost(1, "ImageTest");
Okay will get on that. Thank you!

2022-05-25 12:47 UTC, pyaeger commented on src/test/java/com/amplifier/controllers/ImgPostControllerIntTest.java
> +                            .delete("/api/v1/imgpost?id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
Okay will do. Thx!

2022-05-26 15:10 UTC, L3viathon approved these changes

2022-05-26 15:54 UTC, merged