Updated character controller with CRUD operations
FullSol/amplifier pull request #79
Opened 2022-05-24 15:16 UTC by briiitelord

2022-05-24 16:41 UTC, FullSol requested changes
So, you did this absolutely correct, and I apologize for the request change. This is due to the way we first decided to write the documentation.

2022-05-24 16:41 UTC, FullSol commented on src/main/java/com/amplifier/controllers/CharacterController.java
> +    @PutMapping("/character/{Id}")
You did this correct per the current documentation. I am going to be changing the documentation to a query. That means the URI will be "/character?id={Id}"

2022-05-24 16:41 UTC, FullSol commented on src/main/java/com/amplifier/controllers/CharacterController.java
> +    @DeleteMapping("/character/{Id}")
You did this correct per the current documentation. I am going to be changing the documentation to a query. That means the URI will be "/character?id={Id}"

2022-05-24 16:41 UTC, FullSol commented on src/main/java/com/amplifier/controllers/CharacterController.java
> +    @GetMapping(path = "/character/{id}")
You did this correct per the current documentation. I am going to be changing the documentation to a query. That means the URI will be "/character?id={Id}"

2022-05-25 22:29 UTC, pyaeger requested changes
Just a few little changes requested. Thanks!

2022-05-25 22:29 UTC, pyaeger commented on src/main/java/com/amplifier/controllers/CharacterController.java
> +    @ApiOperation(value = "Find all characters")
Please add notes to ApiOperation documentation and return object in ApiOperation as well if a return type is present.

2022-05-25 22:29 UTC, pyaeger commented on src/main/java/com/amplifier/controllers/CharacterController.java
> +    @ApiOperation(value = "Create new character entity")
Please add ApiOperation note and return where relevant. Thanks!

2022-05-26 13:33 UTC, FullSol approved these changes

2022-05-26 13:51 UTC, pyaeger approved these changes
Looks good.

2022-05-26 13:53 UTC, pyaeger commented
Conflicting files need to be resolved before I can merge this pull request.

2022-05-26 14:58 UTC, FullSol commented
@pyaeger Yeah, this is a process that is really annoying. Go ahead and download GitHub desktop and we will go over this when we get a chance today.

2022-05-26 20:34 UTC, merged