updated UserRolesServiceIntegrationTest
FullSol/amplifier pull request #81
Opened 2022-05-24 17:05 UTC by pyaeger

Will add reviewers once built and ready for review as per Calvin's note in Discord.

2022-05-25 04:21 UTC, pyaeger commented
Built this as far as my current understanding allows.

2022-05-25 11:54 UTC, FullSol reviewed
This looks goo, just missing a couple of methods. We can go over this and complete it this afternoon.

2022-05-25 16:19 UTC, pyaeger commented
Reworked UserRolesService Integration Test based on Calvin's ImgPostService Integration Test.

2022-05-25 17:38 UTC, FullSol approved these changes

2022-05-26 15:17 UTC, L3viathon commented on src/main/java/com/amplifier/services/UserRolesServiceImpl.java
> +	public boolean isValidUserRoleViolated(Integer id, String role) {
I'm a bit confused by this method. I'm not sure what this method is trying to do?

2022-05-26 15:25 UTC, L3viathon requested changes
Outside of the method in the UserRolesServiceImpl, nice! Gonna set it to Request changes just to be on the safe side....

2022-05-26 21:21 UTC, merged