Added Character repository
FullSol/amplifier pull request #84
Opened 2022-05-24 18:59 UTC by L3viathon

2022-05-24 18:59 UTC, L3viathon commented
closes #37

2022-05-24 19:22 UTC, pyaeger approved these changes
Thank you.

2022-05-25 03:59 UTC, FullSol requested changes
Made a few comments for you to follow up on.

Thanks.

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepositoryImpl.java
> +package com.amplifier.repositories;
Delete this file.

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public List<Character> findAll();
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public List<Character> findAll();
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public boolean deleteById(int id);
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public boolean deleteById(int id);
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public boolean update(Character character);
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public boolean update(Character character);
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public Character findById(int id);
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public Character findById(int id);
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public boolean create(Character character);
Annotation needed

2022-05-25 03:59 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepository.java
> +    public boolean create(Character character);
Annotation needed

2022-05-25 04:22 UTC, FullSol approved these changes

2022-05-25 04:22 UTC, FullSol commented on src/main/java/com/amplifier/repositories/CharacterRepositoryImpl.java
> +package com.amplifier.repositories;
Delete this file.

2022-05-25 04:22 UTC, merged